### PR TITLE
A first version of rerun_except.

### PR DESCRIPTION
**Pull request by ltratt**
The doc comments explain this better than I can here. You can see a use of this crate in https://github.com/softdevteam/yksom/commit/4691a3ff221c9e88539241668b3d4166eb195fc8.

### CODE REVIEW

**Comment by vext01** [comment]
Before I review the code properly, let me see if I understand properly.

`rerun-if-env-changed=VAR` *can* be used to narrow the set of paths cargo considers when deciding whether to rebuild, but in certain cases (e.g. when you only want a certain file extension like `*.som`) it'd be tedious.

This allows us to say "everything but files which match this glob" (e.g. `**/*.som`).

Right?

**Comment by ltratt** [comment]
Yep.

**Comment by vext01** [comment]
LGTM, but you've touched some Cargo internals I've never seen before, so my review is superficial :)

Ready to merge?

**Comment by ltratt** [comment]
I need to squash that last commit if you're OK with it?

**Comment by vext01** [comment]
Yep, that's fine. Go ahead.

**Comment by ltratt** [comment]
Squashed.

**Review by vext01 — APPROVED** [review]

**Pull request merged**
